name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: docker-compose -f docker-compose.test.yml up --build
