name: Generate and publish API documentation

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker-compose -f docker-compose.docs.yml up --build --exit-code-from app

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/api
